[package]
name = "rx82"
version = "0.6.0"
edition = "2024"
authors = ["John Arundel <john@bitfieldconsulting.com>"]
description = """An emulator for the RX82 fantasy retro computer system."""
keywords = ["emulator", "emulation", "R8", "RX82", "retrocomputing"]
categories = ["emulators"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/rx82"
homepage = "https://github.com/bitfield/r8/tree/main/crates/rx82"
repository = "https://github.com/bitfield/r8/tree/main/crates/rx82"
exclude = ["/.github/"]

[badges]
github = { repository = "bitfield/r8", workflow = "CI" }
maintenance = { status = "actively-developed" }

[features]
states = []

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
getrandom = "0.4.3"
r8cpu = { path = "../r8cpu", version = "0.1.1" }
r8asm = { path = "../r8asm", version = "0.1.0" }

[lints]
workspace = true
